@startuml

state Start { 
[*] --> SendStartBoot
SendStartBoot --> ReceiveBootEnterRespond
ReceiveBootEnterRespond -left-> SendError
ReceiveBootEnterRespond --> [*]

SendError --> ReceiveBootEnterRespond
}

@enduml